# Generated by Django 3.2.13 on 2022-06-02 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='key',
        ),
        migrations.AddField(
            model_name='user',
            name='email_otp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_otp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
