# Generated by Django 3.2.13 on 2022-06-28 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20220602_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='employee_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Vault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_indian', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_vault', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IndianVault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Aadhar card', 'Aadhar card'), ('Driving Licence', 'Driving Licence'), ('Passport', 'Passport')], max_length=255)),
                ('document', versatileimagefield.fields.VersatileImageField(upload_to='profile/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('vault', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indian_users_vault', to='account.vault')),
            ],
        ),
        migrations.CreateModel(
            name='ForeignersVault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport_photo', versatileimagefield.fields.VersatileImageField(upload_to='profile/')),
                ('visa_photo', versatileimagefield.fields.VersatileImageField(upload_to='profile/')),
                ('address1', models.TimeField(max_length=20000)),
                ('address2', models.TimeField(max_length=20000)),
                ('city', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('zip_code', models.CharField(max_length=255)),
                ('passport_number', models.CharField(max_length=255)),
                ('passport_country_of_issued', models.CharField(max_length=255)),
                ('passport_date_of_issued', models.DateField()),
                ('passport_expire_date', models.DateField()),
                ('visa_issued_date', models.DateField()),
                ('visa_expire_date', models.DateField()),
                ('visa_type', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('vault', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foreigners_users_vault', to='account.vault')),
            ],
        ),
    ]
