# Generated by Django 3.2.13 on 2022-06-30 10:15

from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20220628_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indianvault',
            name='vault',
        ),
        migrations.AddField(
            model_name='vault',
            name='address1',
            field=models.TimeField(blank=True, max_length=20000, null=True),
        ),
        migrations.AddField(
            model_name='vault',
            name='address2',
            field=models.TimeField(blank=True, max_length=20000, null=True),
        ),
        migrations.AddField(
            model_name='vault',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vault',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vault',
            name='document',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='profile/'),
        ),
        migrations.AddField(
            model_name='vault',
            name='passport_country_of_issued',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vault',
            name='passport_date_of_issued',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vault',
            name='passport_expire_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vault',
            name='passport_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vault',
            name='passport_photo',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='profile/'),
        ),
        migrations.AddField(
            model_name='vault',
            name='type',
            field=models.CharField(blank=True, choices=[('Aadhar card', 'Aadhar card'), ('Driving Licence', 'Driving Licence'), ('Passport', 'Passport')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vault',
            name='visa_expire_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vault',
            name='visa_issued_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vault',
            name='visa_photo',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='profile/'),
        ),
        migrations.AddField(
            model_name='vault',
            name='visa_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vault',
            name='zip_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='ForeignersVault',
        ),
        migrations.DeleteModel(
            name='IndianVault',
        ),
    ]
