# Generated by Django 3.2.13 on 2022-06-30 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20220630_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vault',
            name='address1',
            field=models.TextField(blank=True, max_length=20000, null=True),
        ),
        migrations.AlterField(
            model_name='vault',
            name='address2',
            field=models.TextField(blank=True, max_length=20000, null=True),
        ),
    ]
