# Generated by Django 3.2.13 on 2022-08-27 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20220810_0607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vault',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='users_vault', to=settings.AUTH_USER_MODEL),
        ),
    ]
