databases:
  - name: casamelhor
    databaseName: casamelhor
    user: casamelhor

services:
  - type: web
    name: casamelhor
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn casamelhor.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: casamelhor
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4