# Generated by Django 3.2.13 on 2022-07-15 12:52

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_auto_20220706_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenitiesattribute',
            name='ppoi',
            field=versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='amenitiesattribute',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='amenities_attribute/'),
        ),
    ]
