# Generated by Django 3.2.13 on 2022-08-16 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_auto_20220715_1252'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
