# Generated by Django 3.2.13 on 2022-08-16 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_bookingproperty'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookingProperty',
        ),
    ]
