# Generated by Django 3.2.13 on 2022-08-20 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_alter_room_allow_booking_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='room_amenities',
        ),
        migrations.AddField(
            model_name='room',
            name='room_amenities',
            field=models.ManyToManyField(blank=True, related_name='room_amenities', to='property.AmenitiesAttribute'),
        ),
    ]
