# Generated by Django 3.2.13 on 2022-08-22 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_auto_20220820_0922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='property_amenities',
        ),
        migrations.AddField(
            model_name='property',
            name='property_amenities',
            field=models.ManyToManyField(blank=True, related_name='property_amenities', to='property.AmenitiesAttribute'),
        ),
    ]
