# Generated by Django 3.2.13 on 2022-08-23 09:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0010_auto_20220822_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyinactivereasons',
            name='property',
        ),
        migrations.AddField(
            model_name='property',
            name='restrict_booking_managers',
            field=models.ManyToManyField(blank=True, related_name='property_restrict_booking_manager', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='room',
            name='restrict_booking_managers',
            field=models.ManyToManyField(blank=True, related_name='room_restrict_booking_manager', to=settings.AUTH_USER_MODEL),
        ),
    ]
