# Generated by Django 3.2.13 on 2022-08-26 06:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0011_auto_20220823_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(max_length=255)),
                ('br_name', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, max_length=65500, null=True)),
                ('check_in_date', models.DateField(blank=True, null=True)),
                ('check_out_date', models.DateField(blank=True, null=True)),
                ('no_of_night', models.IntegerField()),
                ('status', models.CharField(choices=[('Booking Confirmed', 'Booking Confirmed'), ('Checked-In', 'Checked-In'), ('No Show marked', 'No Show marked'), ('Stay Dates Modified', 'Stay Dates Modified'), ('Checked-Out', 'Checked-Out'), ('Cancelled', 'Cancelled')], max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('booked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_user', to=settings.AUTH_USER_MODEL)),
                ('guest', models.ManyToManyField(blank=True, related_name='booking_guest_users', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_room', to='property.room')),
            ],
        ),
    ]
